name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore SampleWebApplication.sln 
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run:
        msbuild  SampleWebApplication.sln -p:Configuration=Release 
    - name: 'Upload Package'
      uses: actions/upload-artifact@v1
      with:
        name: BuildArtifacts
        path: SampleWebApplication
        
        #Sample  
